name: flutter_cataas
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.6 <4.0.0"

dependencies:
  anyhow: ^3.0.1
  collection: ^1.18.0
  css_colors: ^1.1.5
  dio: ^5.4.3+1
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  flutter_portal: ^1.1.4
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_typeahead: ^5.2.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  icon_decoration: ^2.1.0
  intl: any
  meta: ^1.10.0
  neubrutalism_ui: ^2.0.2
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0
  talker: ^4.2.0
  talker_dio_logger: ^4.1.5

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  glados: ^1.1.6
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
